name: setup-fortran

on:
  push:
    branches:
      - setup-fortran

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 11}
          - {compiler: intel-classic, version: '2021.10'}
        include:
          - os: ubuntu-latest
            toolchain: {compiler: intel, version: '2023.2'}
        exclude:
          - os: windows-latest
            toolchain: {compiler: intel-classic, version: '2021.10'}

    steps:
      - uses: fortran-lang/setup-fortran@v1.3
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - run: ${{ env.FC }} --version
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
