name: setup-fortran

on:
  push:
    branches:
      - setup-fortran

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        toolchain:
          - {compiler: gcc, version: 11}
          - {compiler: intel, version: '2023.2'}
          - {compiler: intel-classic, version: '2021.10'}
        exclude:
          - os: macos-12
            toolchain: {compiler: intel}
          - os: windows-2022
            toolchain: {compiler: gcc}

    steps:
      - uses: fortran-lang/setup-fortran@v1.3
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - run: ${{ env.FC }} /QV
        if: ${{ contains(matrix.toolchain.compiler, 'intel') && runner.os == 'Windows' }}
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}

      - run: ${{ env.FC }} --version
        if: ${{ !(contains(matrix.toolchain.compiler, 'intel') && runner.os == 'Windows') }}
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
  