name: CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  release:
    types:
      - published

env:
  FORCE_COLOR: 3

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: phreeqcrm-src

      - name: List
        run: ls -al

      - name: List up one
        run: ls -al ..

      - name: List up two
        run: ls -al ../..

      - uses: actions/checkout@v3
        with:
            repository: jbeder/yaml-cpp
            ref: yaml-cpp-0.7.0
            path: yaml-cpp-src

      - name: List
        run: ls -al

      - name: List up one
        run: ls -al ..

      - name: List up two
        run: ls -al ../..

      - name: printenv
        run: printenv

    #   - name: Build package
    #     run: pipx run build

    #   - uses: actions/upload-artifact@v3
    #     with:
    #       path: dist/*
