name: cd

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  release:
    types:
      - published

env:
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: phreeqcrm-source

      - uses: actions/checkout@v3
        with:
            repository: jbeder/yaml-cpp
            ref: yaml-cpp-0.7.0
            path: yaml-cpp-source

      - name: Install ninja
        run: sudo apt-get -y install ninja-build

      - name: Configure yaml-cpp
        run: cmake -G "Ninja Multi-Config" -B yaml-cpp-build -S yaml-cpp-source -DYAML_CPP_BUILD_TOOLS:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/yaml-cpp-install

      - name: Build yaml-cpp
        run: cmake --build yaml-cpp-build --config Release

      - name: Test yaml-cpp
        run: ctest --test-dir yaml-cpp-build

      - name: Install yaml-cpp
        run: cmake --install yaml-cpp-build

      - name: find
        run: find ..

      - name: printenv
        env:
          yaml-cpp_DIR: ${{ github.workspace }}/yaml-cpp-install/share/cmake/yaml-cpp
        run: printenv

      - name: list
        env:
          yaml-cpp_DIR: ${{ github.workspace }}/yaml-cpp-install/share/cmake/yaml-cpp
        run: ls -al $yaml-cpp_DIR

      - name: Build package
        env:
          yaml-cpp_DIR: ${{ github.workspace }}/yaml-cpp-install/share/cmake/yaml-cpp
        working-directory: phreeqcrm-source
        run: pipx run build

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
