name: CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  release:
    types:
      - published

env:
  FORCE_COLOR: 3

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: phreeqcrm-source

      - uses: actions/checkout@v3
        with:
            repository: jbeder/yaml-cpp
            ref: yaml-cpp-0.7.0
            path: yaml-cpp-source

      - name: Configure yaml-cpp
        run: cmake -G Ninja -B yaml-cpp-build -S yaml-cpp-source -DCMAKE_BUILD_TYPE=Release -DYAML_CPP_BUILD_TOOLS:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/yaml-cpp-install

      - name: Build yaml-cpp
        run: cmake --build yaml-cpp-build

      - name: Test yaml-cpp
        run: ctest --test-dir yaml-cpp-build

      - name: printenv
        run: printenv

    #   - name: Build package
    #     run: pipx run build

    #   - uses: actions/upload-artifact@v3
    #     with:
    #       path: dist/*
