name: wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: ${{ matrix.python[0] }}(${{ matrix.buildplat[2] }}) on ${{ matrix.buildplat[0] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      matrix:
        buildplat:
          - [macos-13, macosx_x86_64, x86_64]
          - [macos-14, macosx_arm64, arm64]
          - [ubuntu-20.04, manylinux_x86_64, x86_64]
          - [ubuntu-20.04, manylinux_i686, i686]
          # - [windows-2019, win_amd64, x64]
          # - [windows-2019, win32, Win32]
        python:
          - [cp38, v141]
          - [cp39, v141]
          - [cp310, v141]
          - [cp311, v141]
          - [cp312, v142]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build wheels
        if: ${{ runner.os != 'Windows' }}
        uses: pypa/cibuildwheel@7e5a838a63ac8128d71ab2dfd99e4634dd1bca09  # v2.19.2
        env:
          # CIBW_PRERELEASE_PYTHONS: True
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          # CIBW_BUILD_VERBOSITY: 1

      - name: Build wheels (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: pypa/cibuildwheel@7e5a838a63ac8128d71ab2dfd99e4634dd1bca09  # v2.19.2
        env:
          # CIBW_PRERELEASE_PYTHONS: True
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          # CIBW_BUILD_VERBOSITY: 1
          # CMAKE_GENERATOR: Visual Studio 16 2019
          CMAKE_GENERATOR_TOOLSET: ${{ matrix.python[1] }}
          CMAKE_GENERATOR_PLATFORM: ${{ matrix.buildplat[2] }}

      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
